<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/BuildingBlocks.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
