<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Passenger.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Passenger\src\Passenger.csproj" />
    <ProjectReference Include="..\SharedServiceExtensions\SharedServiceExtensions.csproj" />
  </ItemGroup>
</Project>
