<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Flight.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Flight\src\Flight.csproj" />
    <ProjectReference Include="..\SharedServiceExtensions\SharedServiceExtensions.csproj" />
  </ItemGroup>
</Project>
