<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\BuildingBlocks.Core.csproj" />
  </ItemGroup>
</Project>
