<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Duende.IdentityServer.EntityFramework.Storage" Version="7.4.6" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Humanizer.Core" Version="3.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageReference Include="Polly" Version="8.6.5" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="GrpcClient\Protos\flight.proto" GrpcServices="Both" />
    <Protobuf Include="GrpcClient\Protos\passenger.proto" GrpcServices="Both" />
    <Folder Include="GrpcClient\Protos" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Caching\BuildingBlocks.Caching.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Core\BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventStoreDB\BuildingBlocks.EventStoreDB.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Exception\BuildingBlocks.Exception.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Logging\BuildingBlocks.Logging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Mapster\BuildingBlocks.Mapster.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Mongo\BuildingBlocks.Mongo.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Validation\BuildingBlocks.Validation.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\BuildingBlocks.Web.csproj" />
  </ItemGroup>

</Project>
