<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Booking.Host</RootNamespace>
    <AssemblyName>Booking.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EasyCaching.InMemory" Version="1.9.2" />
    <PackageReference Include="Figgle" Version="0.6.5" />
    <PackageReference Include="Figgle.Fonts" Version="0.6.5" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\src\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\Contracts.Grpc\Contracts.Grpc.csproj" />
    <ProjectReference Include="..\..\..\Contracts.Messages\Contracts.Messages.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Core\BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventStoreDB\BuildingBlocks.EventStoreDB.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Grpc\BuildingBlocks.Grpc.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Jwt\BuildingBlocks.Jwt.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MassTransit\BuildingBlocks.MassTransit.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Mongo\BuildingBlocks.Mongo.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PersistMessageProcessor\BuildingBlocks.PersistMessageProcessor.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ProblemDetails\BuildingBlocks.ProblemDetails.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\..\..\Modules\Booking\src\Booking.csproj" />
  </ItemGroup>
</Project>
