<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="EventStore.Client.Grpc.Streams" Version="23.3.9" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/BuildingBlocks.Core.csproj" />
    <ProjectReference Include="../Exception/BuildingBlocks.Exception.csproj" />
    <ProjectReference Include="../Utils/BuildingBlocks.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
