<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="EventStore.Client.Grpc.Streams" Version="23.3.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\Web\BuildingBlocks.Web.csproj" />
  </ItemGroup>
</Project>
