// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.FPS.Data;

#nullable disable

namespace Payments.FPS.Data.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.FPS.OutboundPayments.Models.OutboundPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("reference");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbound_payment");

                    b.ToTable("outbound_payment", (string)null);
                });

            modelBuilder.Entity("Payments.FPS.OutboundPayments.Models.OutboundPayment", b =>
                {
                    b.OwnsOne("Payments.FPS.OutboundPayments.ValueObjects.UkAccount", "CreditorAccount", b1 =>
                        {
                            b1.Property<Guid>("OutboundPaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("creditor_account_account_number");

                            b1.Property<string>("SortCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("creditor_account_sort_code");

                            b1.HasKey("OutboundPaymentId")
                                .HasName("pk_outbound_payment");

                            b1.ToTable("outbound_payment");

                            b1.WithOwner()
                                .HasForeignKey("OutboundPaymentId")
                                .HasConstraintName("fk_outbound_payment_outbound_payment_id");
                        });

                    b.OwnsOne("Payments.FPS.OutboundPayments.ValueObjects.UkAccount", "DebtorAccount", b1 =>
                        {
                            b1.Property<Guid>("OutboundPaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("debtor_account_account_number");

                            b1.Property<string>("SortCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("debtor_account_sort_code");

                            b1.HasKey("OutboundPaymentId")
                                .HasName("pk_outbound_payment");

                            b1.ToTable("outbound_payment");

                            b1.WithOwner()
                                .HasForeignKey("OutboundPaymentId")
                                .HasConstraintName("fk_outbound_payment_outbound_payment_id");
                        });

                    b.OwnsOne("Payments.FPS.OutboundPayments.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("OutboundPaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("OutboundPaymentId")
                                .HasName("pk_outbound_payment");

                            b1.ToTable("outbound_payment");

                            b1.WithOwner()
                                .HasForeignKey("OutboundPaymentId")
                                .HasConstraintName("fk_outbound_payment_outbound_payment_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("CreditorAccount")
                        .IsRequired();

                    b.Navigation("DebtorAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
