<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\BuildingBlocks.Core.csproj" />
  </ItemGroup>
</Project>
