<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>BookingApi</RootNamespace>
    <AssemblyName>Booking.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\src\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Modules\Booking\src\Booking.csproj" />
  </ItemGroup>
</Project>
