<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Booking.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Booking\src\Booking.csproj" />
    <ProjectReference Include="..\SharedServiceExtensions\SharedServiceExtensions.csproj" />
  </ItemGroup>
</Project>
