<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>BookingService</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\src\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Modules\Booking\src\Booking.csproj" />
  </ItemGroup>
</Project>
